name: WDIO Automation
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test -- --suite registration
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
